Look-Up Table Dataloaders
antarctica/CartograPhi pull request #7
Opened 2023-09-22 11:32 UTC by hjabbot

# CartograPhi Pull Request Template

Date: 2023-09-22
Version Number:1.1.0
 
## Description of change
Added Look-Up Table dataloaders, which enable the use of shapely Polygons as data inputs. For example, an exclusion zone can be defined using a GeoJSON, SHP or CSV file, without generating 'fake' datapoints such as with the old Density and Thickness dataloaders. On that note, both density and thickness dataloaders have been changed to the LUT format.

I've also folded in changes to 1.0.x into this so that 1.1.x is up to date with the recent changes

## Fixes # https://github.com/antarctica/AMOP-project/issues/141

# Testing
To ensure that the functionality of the CartograPhi codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 

- [ ] My changes have not altered any of the files listed in the testing strategy

- [x] My changes result in all required regression tests passing without the need to update test files.  
  
[Passing tests](https://github.com/antarctica/CartograPhi/files/12700205/reg_test_lut.txt)
> Following files changed:
> * boundary.py
> * aggregated_cellbox.py
> * neighbour_graph.py

- [ ] My changes require one or more test files to be updated for all regression tests to pass.   

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [ ] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [x] My PR has been made to the `1.1.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2023-09-22 13:40 UTC, gecoombs commented on cartographi/__init__.py
> +__version__ = "1.1.0"
There is a conflict with the base branch here that needs to be resolved before merging

2023-09-22 14:12 UTC, gecoombs commented
Shouldn't the docs be updated to include the new dataloaders? Or are we planning a separate PR to update the docs after all the mesh separation work?

2023-09-25 09:04 UTC, SamuelHall700 requested changes
Looks good, we should really be updating the docs with this PR as well though - even if it's just the addition of .rst files for the new data loaders that are auto-generated from the docstrings. We can do a once-over of the docs to add more information sometime after the ship visit

2023-09-25 09:12 UTC, ayat-khairy approved these changes
Looks good

2023-09-29 08:33 UTC, gecoombs approved these changes
Seems legit 👍

2023-10-02 07:48 UTC, SamuelHall700 approved these changes
Looks good!

2023-10-02 08:43 UTC, merged